# Generated by Django 3.2.6 on 2022-03-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_index', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('rated_date', models.DateTimeField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recommend_all.signup')),
            ],
            options={
                'unique_together': {('user', 'movie_index')},
            },
        ),
    ]
